#define TAPPING_TERM 100
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define COMBO_COUNT 8
#define COMBO_TERM 30
#define LEADER_TIMEOUT 300
#define MOUSEKEY_WHEEL_DELAY 200
#define MOUSEKEY_WHEEL_MAX_SPEED 1